name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: eregon/use-ruby-action@v1
        with:
          ruby-version: 3.0

      - name: Cache vendor/bundle
        uses: actions/cache@v1
        id: cache_gem
        with:
          path: vendor/bundle
          key: v1-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            v1-gem-
      - name: bundle install
        run: |
          set -xe
          bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Run Itamae
        run: |
          set -xe
          bundle exec itamae ssh -u root -h 118.27.117.19 recipe.rb
